// transit copy from PR #92 (feature/92-generation-engine-catalogs @ fc192cb7db) — dedupe at merge
// AUTO-CURATED from server/src/modules/ai/helpers/componentsMeta.json (property names/coverage
// only) and frontend/src/AppBuilder/WidgetManager/widgets/*.js (`events` blocks, for triggers).
// Restructured per ADR-0033: not a port of componentsMeta.json's validation-schema shape, no
// EE code/prompts reused -- see docs/adr/0033-generation-engine-component-event-catalogs.md.
//
// The `Modal` entry's properties and triggers both come from widgets/modal.js (the legacy
// widget componentsMeta.json's `Modal` key describes -- useDefaultButton/triggerButtonLabel/
// hideOnEsc are its shape, not modalV2.js's), confirmed events: { onOpen, onClose } match.
import type { ComponentCatalogEntry } from './types';

export const COMPONENT_CATALOG: Record<string, ComponentCatalogEntry> = {
  Table: {
    name: 'Table',
    category: 'data',
    properties: [
      { name: 'title', valueType: 'string' },
      { name: 'visible', valueType: 'dynamic' },
      { name: 'loadingState', valueType: 'boolean', defaultValue: false },
      { name: 'dataSourceSelector', valueType: 'dynamic' },
      { name: 'data', valueType: 'array' },
      { name: 'useDynamicColumn', valueType: 'boolean', defaultValue: false },
      { name: 'columnData', valueType: 'array' },
      { name: 'rowsPerPage', valueType: 'number', defaultValue: 10 },
      { name: 'serverSidePagination', valueType: 'boolean', defaultValue: false },
      { name: 'enableNextButton', valueType: 'boolean', defaultValue: true },
      { name: 'enablePrevButton', valueType: 'boolean' },
      { name: 'totalRecords', valueType: 'number', defaultValue: 10 },
      { name: 'enablePagination', valueType: 'boolean', defaultValue: true },
      { name: 'serverSideSort', valueType: 'boolean', defaultValue: false },
      { name: 'serverSideFilter', valueType: 'boolean', defaultValue: false },
      { name: 'displaySearchBox', valueType: 'boolean', defaultValue: true },
      { name: 'showDownloadButton', valueType: 'boolean', defaultValue: true },
      { name: 'showFilterButton', valueType: 'boolean', defaultValue: true },
      { name: 'autogenerateColumns', valueType: 'dynamic' },
      { name: 'isAllColumnsEditable', valueType: 'dynamic' },
      { name: 'columns', valueType: 'dynamic' },
      { name: 'showBulkUpdateActions', valueType: 'boolean', defaultValue: true },
      { name: 'showBulkSelector', valueType: 'boolean', defaultValue: false },
      { name: 'highlightSelectedRow', valueType: 'boolean', defaultValue: false },
      { name: 'columnSizes', valueType: 'dynamic' },
      { name: 'actions', valueType: 'dynamic' },
      { name: 'enabledSort', valueType: 'boolean', defaultValue: true },
      { name: 'hideColumnSelectorButton', valueType: 'boolean', defaultValue: false },
      { name: 'defaultSelectedRow', valueType: 'object', defaultValue: { id: 1 } },
      { name: 'showAddNewRowButton', valueType: 'boolean', defaultValue: true },
      { name: 'showRefreshButton', valueType: 'boolean', defaultValue: false },
      { name: 'allowSelection', valueType: 'boolean', defaultValue: true },
      { name: 'visibility', valueType: 'boolean' },
      { name: 'collapseWhenHidden', valueType: 'boolean', defaultValue: false },
      { name: 'disabledState', valueType: 'boolean' },
      { name: 'dynamicHeight', valueType: 'boolean', defaultValue: false },
      { name: 'selectRowOnCellEdit', valueType: 'boolean', defaultValue: false },
      { name: 'enableExpandableRows', valueType: 'boolean', defaultValue: false },
      { name: 'expansionHeight', valueType: 'number', defaultValue: 229 },
      { name: 'disableRowDeselection', valueType: 'boolean', defaultValue: false },
      { name: 'serverSideRowsPerPage', valueType: 'dynamic' },
      { name: 'serverSideSearch', valueType: 'boolean', defaultValue: false },
      { name: 'actionButtonBackgroundColor', valueType: 'string', defaultValue: '#375FCF' },
      { name: 'actionButtonTextColor', valueType: 'string', defaultValue: '#fff' },
    ],
    triggers: [
      { id: 'onRowHovered', displayName: 'Row hovered' },
      { id: 'onRowClicked', displayName: 'Row clicked' },
      { id: 'onExpand', displayName: 'Row expanded' },
      { id: 'onBulkUpdate', displayName: 'Save changes' },
      { id: 'onPageChanged', displayName: 'Page changed' },
      { id: 'onSearch', displayName: 'Search' },
      { id: 'onCancelChanges', displayName: 'Cancel changes' },
      { id: 'onSort', displayName: 'Sort applied' },
      { id: 'onCellValueChanged', displayName: 'Cell value changed' },
      { id: 'onFilterChanged', displayName: 'Filter changed' },
      { id: 'onNewRowsAdded', displayName: 'Add new rows' },
      { id: 'onTableDataDownload', displayName: 'Download data' },
      { id: 'onRefresh', displayName: 'Refresh' },
      { id: 'onHeaderClick', displayName: 'Header clicked' },
    ],
  },
  Button: {
    name: 'Button',
    category: 'input',
    properties: [
      { name: 'text', valueType: 'string' },
      { name: 'visibility', valueType: 'boolean' },
      { name: 'collapseWhenHidden', valueType: 'boolean', defaultValue: false },
      { name: 'disabledState', valueType: 'boolean' },
      { name: 'loadingState', valueType: 'boolean' },
      { name: 'tooltip', valueType: 'string' },
      { name: 'tooltipFormat', valueType: 'dynamic' },
    ],
    triggers: [
      { id: 'onClick', displayName: 'Clicked' },
      { id: 'onHover', displayName: 'Hovered' },
    ],
  },
  Text: {
    name: 'Text',
    category: 'display',
    properties: [
      { name: 'textFormat', valueType: 'dynamic' },
      { name: 'dynamicHeight', valueType: 'boolean', defaultValue: false },
      { name: 'text', valueType: 'string', defaultValue: 'Hello, there!' },
      { name: 'loadingState', valueType: 'boolean', defaultValue: false },
      { name: 'disabledState', valueType: 'boolean', defaultValue: false },
      { name: 'visibility', valueType: 'boolean', defaultValue: true },
      { name: 'collapseWhenHidden', valueType: 'boolean', defaultValue: false },
      { name: 'tooltipFormat', valueType: 'dynamic' },
      { name: 'tooltip', valueType: 'string', defaultValue: 'Tooltip text' },
    ],
    triggers: [
      { id: 'onClick', displayName: 'Clicked' },
      { id: 'onHover', displayName: 'Hovered' },
    ],
  },
  TextInput: {
    name: 'TextInput',
    category: 'input',
    properties: [
      { name: 'value', valueType: 'string', defaultValue: 'Default value' },
      { name: 'label', valueType: 'string', defaultValue: 'Label' },
      { name: 'placeholder', valueType: 'string', defaultValue: 'Enter your input' },
      { name: 'visibility', valueType: 'boolean', defaultValue: true },
      { name: 'collapseWhenHidden', valueType: 'boolean', defaultValue: false },
      { name: 'disabledState', valueType: 'boolean', defaultValue: false },
      { name: 'loadingState', valueType: 'boolean', defaultValue: false },
      { name: 'tooltip', valueType: 'string', defaultValue: 'Tooltip text' },
      { name: 'tooltipFormat', valueType: 'dynamic' },
      { name: 'showClearBtn', valueType: 'boolean', defaultValue: false },
    ],
    triggers: [
      { id: 'onChange', displayName: 'Value changed' },
      { id: 'onEnterPressed', displayName: 'Enter pressed' },
      { id: 'onFocus', displayName: 'Focused' },
      { id: 'onBlur', displayName: 'Blurred' },
    ],
  },
  Container: {
    name: 'Container',
    category: 'layout',
    properties: [
      { name: 'showHeader', valueType: 'boolean', defaultValue: true },
      { name: 'loadingState', valueType: 'boolean', defaultValue: false },
      { name: 'visibility', valueType: 'boolean', defaultValue: true },
      { name: 'collapseWhenHidden', valueType: 'boolean', defaultValue: false },
      { name: 'disabledState', valueType: 'boolean', defaultValue: false },
      { name: 'dynamicHeight', valueType: 'boolean', defaultValue: false },
      { name: 'headerHeight', valueType: 'dynamic' },
      { name: 'tooltipFormat', valueType: 'dynamic' },
      { name: 'tooltip', valueType: 'string' },
    ],
    triggers: [],
  },
  Form: {
    name: 'Form',
    category: 'layout',
    properties: [
      { name: 'loadingState', valueType: 'boolean', defaultValue: false },
      { name: 'dynamicHeight', valueType: 'boolean', defaultValue: false },
      { name: 'advanced', valueType: 'dynamic' },
      { name: 'JSONSchema', valueType: 'dynamic' },
      { name: 'newJsonSchema', valueType: 'object' },
      { name: 'showHeader', valueType: 'dynamic' },
      { name: 'showFooter', valueType: 'dynamic' },
      { name: 'visibility', valueType: 'boolean', defaultValue: true },
      { name: 'collapseWhenHidden', valueType: 'boolean', defaultValue: false },
      { name: 'disabledState', valueType: 'boolean', defaultValue: false },
      { name: 'headerHeight', valueType: 'dynamic', defaultValue: 80 },
      { name: 'footerHeight', valueType: 'dynamic', defaultValue: 80 },
      { name: 'validateOnSubmit', valueType: 'boolean', defaultValue: true },
      { name: 'resetOnSubmit', valueType: 'boolean', defaultValue: true },
      { name: 'generateFormFrom', valueType: 'dynamic' },
      { name: 'JSONData', valueType: 'object' },
      { name: 'tooltipFormat', valueType: 'dynamic' },
      { name: 'tooltip', valueType: 'string' },
      { name: 'buttonToSubmit', valueType: 'string', defaultValue: 'none' },
      { name: 'fields', valueType: 'dynamic' },
      { name: 'canvasHeight', valueType: 'dynamic', defaultValue: 80 },
    ],
    triggers: [
      { id: 'onSubmit', displayName: 'Submitted' },
      { id: 'onInvalid', displayName: 'Validation failed' },
    ],
  },
  Chart: {
    name: 'Chart',
    category: 'data',
    properties: [
      { name: 'title', valueType: 'string', defaultValue: 'This title can be changed' },
      { name: 'markerColor', valueType: 'string', defaultValue: 'var(--cc-primary-brand)' },
      { name: 'showAxes', valueType: 'boolean', defaultValue: true },
      { name: 'showGridLines', valueType: 'boolean', defaultValue: true },
      { name: 'plotFromJson', valueType: 'boolean', defaultValue: false },
      { name: 'loadingState', valueType: 'boolean', defaultValue: false },
      { name: 'barmode', valueType: 'dynamic', defaultValue: 'group' },
      { name: 'jsonDescription', valueType: 'dynamic' },
      { name: 'type', valueType: 'dynamic', defaultValue: 'line' },
      { name: 'data', valueType: 'dynamic' },
    ],
    triggers: [
      { id: 'onClick', displayName: 'On data point click' },
      { id: 'onDoubleClick', displayName: 'On double click' },
    ],
  },
  Image: {
    name: 'Image',
    category: 'display',
    properties: [
      { name: 'imageFormat', valueType: 'dynamic' },
      { name: 'source', valueType: 'string', defaultValue: 'https://www.svgrepo.com/image.svg' },
      { name: 'jsSchema', valueType: 'object' },
      { name: 'alternativeText', valueType: 'string', defaultValue: 'this is an image' },
      { name: 'zoomButtons', valueType: 'boolean', defaultValue: false },
      { name: 'rotateButton', valueType: 'boolean', defaultValue: false },
      { name: 'loadingState', valueType: 'boolean', defaultValue: false },
      { name: 'disabledState', valueType: 'boolean', defaultValue: false },
      { name: 'visibility', valueType: 'boolean', defaultValue: true },
      { name: 'collapseWhenHidden', valueType: 'boolean', defaultValue: false },
      { name: 'tooltip', valueType: 'string', defaultValue: 'Tooltip text' },
      { name: 'tooltipFormat', valueType: 'dynamic' },
    ],
    triggers: [{ id: 'onClick', displayName: 'Clicked' }],
  },
  Checkbox: {
    name: 'Checkbox',
    category: 'input',
    properties: [
      { name: 'label', valueType: 'string' },
      { name: 'defaultValue', valueType: 'boolean' },
      { name: 'visibility', valueType: 'boolean' },
      { name: 'collapseWhenHidden', valueType: 'boolean', defaultValue: false },
      { name: 'disabledState', valueType: 'boolean' },
      { name: 'loadingState', valueType: 'boolean' },
      { name: 'tooltip', valueType: 'string' },
      { name: 'tooltipFormat', valueType: 'dynamic' },
    ],
    triggers: [
      { id: 'onChange', displayName: 'On change' },
      { id: 'onCheck', displayName: 'Checked' },
      { id: 'onUnCheck', displayName: 'Unchecked' },
    ],
  },
  DropdownV2: {
    name: 'DropdownV2',
    category: 'input',
    properties: [
      { name: 'advanced', valueType: 'boolean' },
      { name: 'schema', valueType: 'dynamic' },
      { name: 'options', valueType: 'dynamic' },
      { name: 'label', valueType: 'string', defaultValue: 'Select' },
      { name: 'optionsLoadingState', valueType: 'boolean' },
      { name: 'sort', valueType: 'string', defaultValue: 'none' },
      { name: 'placeholder', valueType: 'string', defaultValue: 'Select an option' },
      { name: 'showClearBtn', valueType: 'boolean', defaultValue: true },
      { name: 'showSearchInput', valueType: 'boolean', defaultValue: true },
      { name: 'serverSideSearch', valueType: 'boolean', defaultValue: false },
      { name: 'visibility', valueType: 'boolean', defaultValue: true },
      { name: 'collapseWhenHidden', valueType: 'boolean', defaultValue: false },
      { name: 'disabledState', valueType: 'boolean', defaultValue: false },
      { name: 'loadingState', valueType: 'boolean', defaultValue: false },
      { name: 'tooltip', valueType: 'string', defaultValue: 'Enter tooltip text' },
      { name: 'tooltipFormat', valueType: 'dynamic' },
    ],
    triggers: [
      { id: 'onSelect', displayName: 'Option selected' },
      { id: 'onSearchTextChanged', displayName: 'Search text changed' },
      { id: 'onFocus', displayName: 'Focused' },
      { id: 'onBlur', displayName: 'Blurred' },
    ],
  },
  Modal: {
    name: 'Modal',
    category: 'layout',
    properties: [
      { name: 'title', valueType: 'string', defaultValue: 'This title can be changed' },
      { name: 'titleAlignment', valueType: 'dynamic' },
      { name: 'loadingState', valueType: 'boolean', defaultValue: false },
      { name: 'useDefaultButton', valueType: 'boolean', defaultValue: true },
      { name: 'triggerButtonLabel', valueType: 'string', defaultValue: 'Launch Modal' },
      { name: 'size', valueType: 'string', defaultValue: 'lg' },
      { name: 'hideTitleBar', valueType: 'dynamic' },
      { name: 'hideCloseButton', valueType: 'dynamic' },
      { name: 'hideOnEsc', valueType: 'dynamic' },
      { name: 'closeOnClickingOutside', valueType: 'dynamic' },
      { name: 'modalHeight', valueType: 'string', defaultValue: '400px' },
    ],
    triggers: [
      { id: 'onOpen', displayName: 'Opened' },
      { id: 'onClose', displayName: 'Closed' },
    ],
  },
};
