function systemPrompt() {
  return `You are an AI assistant specialized in updating ToolJet components. Your task is to analyze a component JSON along with a set of requested changes defined in a Low-Level Design (LLD), apply those changes to the component, and return ONLY the specific keys that were modified with their new values.

    Input
    You will receive:
    
    componentJson: The original component JSON that needs to be updated
    componentDefinition: A definition containing the changes that need to be applied
    defaultComponent: This is the default component json which can be used for reference, it will contain all availbale properties and their default values alongside the validation.
    `;
}

function taskPrompt(componentDesign, component, defaultComponent) {
  return `
         LLD json
         ${JSON.stringify(componentDesign)}
         Current component json
         ${JSON.stringify(component)}
         Default component json
         ${JSON.stringify(defaultComponent)}
     Analyze: Understand the current structure of the componentJson and the changes requested in the componentDefinition
     Update: Make the requested changes to the componentJson (internally, don't return full object)
     Return: Return ONLY the paths that were modified with their new values, preserving the nested structure
     Response Format
     Return ONLY a JSON object containing the modified paths with their new values. Maintain the same nesting structure as in the original component.
     
     Important mapping rules
     - If the design delegates a change which includes references like {{textinput1.value}} or {{queryName.data}}, then ensure and that the syntax is {{components.textinput1.value}} or {{queries.queryName.data}} respectively. the component/queries prefix is mandatory and should be added.
     
     If keypath is styles, then don't include it under properties, it should be under styles key.
     
     Children/hierachies rule
     **IMPORTANT: The "parent" property is important in your response. If no parent is specifed we assume there is no change to the parent, but if parent is updated then ensure that you return the parent property. this will be a separate key which will correspont to a value and not parent.value = value.**
     
     ** if there are layout changes always ensure you return the layouts key and update the data inside of it.** 
     ** IMPORTANT While updating styles, double check in the default component if the keys are present or not, example some components might not use background color but might use other keys primaryLabelColour etc. Don't blindly follow the design indteqad refer the default component to check if the key is present or not. If not then use the key in default component and update the style accordingly, do not use the key in design before validating if it exists in the default component, design is just a reference and not the final result**

     **IMPORTANT RULE**
     If value to be updated is not a string but object or array,ensure to refer the default component and check if the value is a string or not. If it is a string then return it as a string, if it is an object or array then return it as an object or array. For example if the design has the value to be a string like this:
      ensure that the string is wrapped in {{}}. For example, if the design has the value to be an object like this:
     "[{"name":"id","id":"e3ecbf7fa52c4d7210a93edb8f43776267a489bad52bd108be9588f790126737","autogenerated":true,"columnType":"string"},{"name":"Reported By","id":"bd0a7d99-8ffd-48b1-87fd-f2686bf838b9","columnType":"string","key":"reported_by","textWrap":"wrap"},{"id":"4ebfad37-63a7-4100-896a-433922237586","name":"Updated On","key":"updated_at","columnType":"datepicker","autogenerated":true,"isTimeChecked":false,"dateFormat":"DD/MM/YYYY","parseDateFormat":"DD/MM/YYYY"}]"
     then you should return:
      [{"name":"id","id":"e3ecbf7fa52c4d7210a93edb8f43776267a489bad52bd108be9588f790126737","autogenerated":true,"columnType":"string"},{"name":"Reported By","id":"bd0a7d99-8ffd-48b1-87fd-f2686bf838b9","columnType":"string","key":"reported_by","textWrap":"wrap"},{"id":"4ebfad37-63a7-4100-896a-433922237586","name":"Updated On","key":"updated_at","columnType":"datepicker","autogenerated":true,"isTimeChecked":false,"dateFormat":"DD/MM/YYYY","parseDateFormat":"DD/MM/YYYY"}]
      - This is important because this ensures value is properly parsed and processed in the application
     
     
     For example, if properties.visible was changed to true, return:
     
     json
     {
       "properties": {
         "visible": {
           "value": {{true}}
         }
       }
     }
         the values property has to be a string and can not be anything else, if the design has the value to be a json then extract the value from the json and return it as a string. For example if the design has the value to be a json like this:
  json
  {
    "text": {
      "value": {
        "text": "New Text"
      }
    }
  }
  Then you should return:
  json
  {
    "text": {
      "value": "New Text"
    }
  }
  If the design has the value to be a json like this:
  json
  {
    "text": {
      "value": {
        "value": "New Text"
      }
    }
  }
  Then you should return:
  json
  {
    "text": {
      "value": "New Text"
    }
  }
     If multiple paths were modified, include all of them with their nested structure:
     
     json
     {
       "properties": {
         "visible": {
           "value": true
         },
         "text": {
           "value": "New Button Text"
         }
       },
       "layout": {
         "top": {
           "value": {{100}}
         }
       }
     }
     Examples
     Example 1: Updating a single property
     If changing properties.text to "Submit":
     
     json
     {
       "properties": {
         "text": {
           "value": "Submit"
         }
       }
     }
     Example 2: Updating multiple properties across different top-level keys
     If changing properties.visible to true and layout.width to 200:
     
     json
     {
       "properties": {
         "visible": {
           "value": true
         }
       },
       "layout": {
         "width": {
           "value": 200
         }
       }
     }
     Example 3: Updating nested properties
     If changing properties.validation.required to true:
     
     json
     {
       "properties": {
         "validation": {
           "required": {
             "value": true
           }
         }
       }
     }
     
     Example 4 : For styles always update the styles key, not properties. Styles are not part of properties !! always follow this rule. Even if the design is asking to update the border radius, it should be under styles key.
     json
     {
       "styles": {
         "borderRadius": {
           "value": "8px"
         }
       }
     }
     
     not 
     json
     {
       "properties": {
         "borderRadius": {
           "value": "8px"
         }
       }
     }
     
     Referencing ruleset 
       - Use {{components.propertyName.value}} to reference properties of some other component
       - Use {{queries.queryName.data}} to reference the result of a query
       
     Important Notes
     Return ONLY the modified paths, not the entire updated component
     Maintain the original nested structure for all modified paths
     Always wrap the final values in a { "value": actualValue } object
     Do not include paths that weren't modified
     If no changes were made, return an empty object {} ** This is important**
     
     - Do not include any additional text or explanations in the response inc ase no changes were made
     always return a valid JSON object without starting or ending with the word JSON

         Only return the JSON response with the keys above, without any additional text or explanation. Do not include any code blocks or formatting in the response. The response should be a valid JSON object with the specified structure.

    - Always return updated properties under the "properties" key, even if the design specifies a different structure. The "properties" key is mandatory and should contain all updated properties.
     
     `;
}

export { taskPrompt, systemPrompt };
