export enum FEATURE_KEY {
  PING = 'ping',
  FETCH_ZERO_STATE = 'fetchZeroState',
  SEND_USER_MESSAGE = 'sendUserMessage',
  SEND_DOCS_MESSAGE = 'sendDocsMessage',
  PROMOTE_CONVERSATION = 'promoteConversation',
  APPROVE_PRD = 'approvePrd',
  PREVIEW_PLAN = 'previewPlan',
  REWIND_STEP = 'rewindStep',
  SKIP_STEP = 'skipStep',
  REGENERATE_MESSAGE = 'regenerateMessage',
  VOTE_MESSAGE = 'voteMessage',
  FIX_WITH_AI = 'fixWithAi',
  COPILOT = 'copilot',
  GET_CREDITS_BALANCE = 'getCreditsBalance',
  LIST_CONVERSATIONS = 'listConversations',
  CREATE_CONVERSATION = 'createConversation',
  GET_CONVERSATION = 'getConversation',
  UPDATE_KEY = 'updateKey',
  GET_KEY_SETTINGS = 'getKeySettings',
  AUTO_SORT_QUERIES = 'autoSortQueries',
  GET_THREAD_TOKEN_USAGE = 'getThreadTokenUsage',
}
